config/routes.rb
Rails.application.routes.draw do
  get 'display_software_info/display_info'
  use_doorkeeper do
    skip_controllers :applications, :authorized_applications
  end

  namespace :api do
    post "login"  => "sessions#create"
    delete "logout" => "sessions#destroy"
    resources :users
  end

  get "login" 	=> "sessions#login"
  post "login" 	=> "sessions#create"
  delete "logout" 	=> "sessions#destroy"

  get "dashboard" => "dashboard#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :access_tokens, class_name: "Doorkeeper::AccessToken",
    foreign_key: :resource_owner_id, dependent: :destroy

    class << self
    	def authenticate params
    		user = User.find_by name: params[:name]
    		return false unless user
    		user.authenticate params[:password]
    	end
    end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
  before_action :doorkeeper_authorize!
  before_action :current_user

  def doorkeeper_unauthorized_render_options error
    {json: {errors: I18n.t("doorkeeper.errors.messages.unauthorized_client", uid: current_user&.id)}}
  end

  def current_user
    @current_user ||= User.find_by(id: doorkeeper_token.resource_owner_id) if doorkeeper_token
  end
end

app/controllers/api/sessions_controller.rb
class Api::SessionsController < Api::ApplicationController
  skip_before_action :doorkeeper_authorize!, only: :create

  def create
    user = User.authenticate users_params
    if user
      render json: {data: Api::GenerateTokenService.new(user).call}, status: 200
    else
      render json: {errors: I18n.t("errors.api.sessions_controller.login.failed")}, status: 400
    end
  end

  def destroy
    revoke_token_service = Api::RevokeTokenService.new doorkeeper_token.token
    revoke_token_service.execute
    if revoke_token_service.success?
      render json: {}, status: 200
    else
      render json: {errors: revoke_token_service.errors}, status: 400
    end
  end

  private
  def users_params
    params.require(:user).permit :name, :password
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApplicationController
  before_action :users, only: :index

  def index
    render json: @users, status: 200
  end

  private
  def users
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper

	before_action :require_login

	def require_login
		unless logged_in?
			redirect_to login_path
		end
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def dashboard
  	# @list_top_menu = { :icon => "test", :title => "Logout" }.to_json
  end
end

app/controllers/display_software_info_controller.rb
class DisplaySoftwareInfoController < ApplicationController
  def display_info
  	@users = User.all
  	@title = 'test'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :require_login, only: [:login, :create]

  def login
  end

  def create
  	user = User.find_by name: params[:session][:name].downcase
  	if user && user.authenticate(params[:session][:password])
  		#TODO save user infor into session
  		flash[:success] = "Login success"
  		log_in user
  		redirect_to dashboard_path
  	else
  		flash[:danger] = "Tên đăng nhập/mật khẩu không đúng, vui lòng thử lại!"
  		render :login
  	end
  end

  def destroy
  	log_out
  	flash[:success] = "Bạn đã đăng xuất, vui lòng đăng nhập lại!"
  	redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :require_login, only: [:new, :create]
	def index
		@users = User.all
	end

	def show
		@user = User.find_by id: params[:id]
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new user_params
		if @user.save
			flash[:success] = "Register successs"
			redirect_to users_path
		else
			flash[:fail] = "Register fail"
			render :new
		end
	end

	private
	def user_params
		params.require(:user).permit :name, :password, :password_confirmation
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/display_software_info_helper.rb
module DisplaySoftwareInfoHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in user
		session[:user_id] = user.id
	end

	def log_out
		session.delete :user_id
	end

	# get current_user
	def current_user
		@current_user ||= User.find_by id: session[:user_id]
	end

	# check user has logged in before ?
	def logged_in?
		current_user.present?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/dashboard.html.haml
.topbar
	.container-fluid
		%a{"href" => "javascript:void(0)", "class" => "company"} Net Admin Template
		%form
			%input{"type" => "text", "value" => "Search here..."}
		%ul.mini
			- @list_top_menu = [{ :icon => "book-question.png", :title => "Support tickets"}.as_json,
			{ :icon => "document-task.png", :title => "Pending orders"}.as_json,
			{ :icon => "balloons-white.png", :title => "Messages"}.as_json,
			{ :icon => "gear.png", :title => "Setting"}.as_json]
			- @list_top_menu.each do |value|
				%li
					%a{"href" => "javascript:void(0)"}
						%img(src="/assets/icons/fugue/#{value["icon"]}") #{value["title"]}
			%li
				= link_to logout_path, method: :delete do
					%img(src="/assets/icons/fugue/control-power.png") Logout
.breadcrumbs
	.container-fluid
		%ul{"class" => "bread pull-left"}
			%li
				%a{"href" => "javascript:void(0)"}
					%i{"class" => "icon-home icon-white"}
			%li
				%a{"href" => "javascript:void(0)"} Dashboard
.main
	.container-fluid
		.navi
			%ul.main-nav
				- @list_left_menu = [{:icon => "icon-home", :title => "Dashboard", :label_class => "label-warning", :label_number => 10 }.as_json,
				{:icon => "icon-list", :title => "Forms", :label_class => "label-info", :label_number => 1 }.as_json,
				{:icon => "icon-th-large", :title => "Tables", :sub => true}.as_json,
				{:icon => "icon-th-large", :title => "Tables", :sub => true}.as_json,
				{:icon => "icon-th-large", :title => "Tables", :sub => true}.as_json,
				{:icon => "icon-th-large", :title => "Tables", :sub => true}.as_json,
				{:icon => "icon-th-large", :title => "Tables", :sub => true}.as_json,
				{:icon => "icon-th-large", :title => "Tables", :sub => true}.as_json]
				- @list_left_menu.each do |value|
					%li
						%a{"href" => "javascript:void(0)", :class => ["light", ("toggle-collapsed" if value["sub"] )]}
							.ico
								%i{"class" => "#{value["icon"]} icon-white"}
							#{value["title"]}
							- if value["label_class"]
								%span{"class" => "label #{value["label_class"]}"} #{value["label_number"]}
							- if value["sub"]
								%img{"src" => "/assets/toggle-subnav-down.png"}
						- if value["sub"]
							%ul{"class" => "collapsed-nav closed"}
								- @list_sub = ['Data Tables', 'Plain Tables', 'Media Tables']
								- @list_sub.each do |value|
									%li
										%a{"href" => "javascript:void(0)"} #{value}
		.content
			%div{"class" => "row-fluid no-margin"}
				.span12
					%ul.quickstats
						- @list_quick = [{:color => "6a9d29", :stroke => "345010", :type => "line", :data1 => "5,3,9,6,5,9,7,3,5,10", :data2 => "+ 9834.41 $", :data3 => "Current balance", :class_data2 => "green"}.as_json,
						{:color => "2c5b96", :stroke => "102c50", :type => "bar", :data1 => "2,5,4,6,5,4,7,8", :data2 => "128.32", :data3 => "Orders per month"}.as_json,
						{:color => "962c2c", :stroke => "651111", :type => "pie", :data1 => "6/10", :data2 => "60%", :data3 => "Member qoute"}.as_json,
						{:color => "2c5b96", :stroke => "102c50", :type => "line", :data1 => "521,500,481,429,550,521", :data2 => "521.3 / month", :data3 => "Unique visitors rate"}.as_json];
						- @list_quick.each do |value|
							%li
								.small-chart{:data => {:color => "#{value["color"]}", :stroke => "#{value["stroke"]}", :type => "#{value["type"]}"}} #{value["data1"]}
								.chart-detail
									%span{:class => ["amount", ("green" if value["class_data2"] )]} #{value["data2"]}
									%span.description #{value["data3"]}
			%div{"class" => "row-fluid no-margin"}
				.span12
					%ul.quicktasks
						- @list_quick1 = [{ :icon => "order-149.png", :title => "Check orders"}.as_json,
						{ :icon => "calendar.png", :title => "Upcoming events"}.as_json,
						{ :icon => "basket.png", :title => "New product"}.as_json,
						{ :icon => "communication.png", :title => "Support tickets"}.as_json,
						{ :icon => "hire-me.png", :title => "Approve user"}.as_json,
						{ :icon => "full-time.png", :title => "Manage cronjobs"}.as_json,
						{ :icon => "invoice.png", :title => "Invoices"}.as_json,
						{ :icon => "bank.png", :title => "Balance"}.as_json,
						{ :icon => "statistics.png", :title => "Site statistics"}.as_json,
						{ :icon => "shipping.png", :title => "Check shipping"}.as_json,
						{ :icon => "bestseller.png", :title => "Bestseller"}.as_json,
						{ :icon => "config.png", :title => "Configuration"}.as_json,
						{ :icon => "heart.png", :title => "My Favourites"}.as_json]
						- @list_quick1.each do |value|
							%li
								%a{"href" => "javascript:void(0)"}
									%img(src="/assets/icons/essen/32/#{value["icon"]}")
									%span #{value["title"]}
			.row-fluid
				.span12
					.box
						.box-head
							%h3 Chart
							.actions
								%ul
									%li.dropdown
										%a{"href" => "javascript:void(0)", "class" => "btn btn-mini dropdown-toggle", :data => {:toggle =>"dropdown"}}
											%img{"src" => "/assets/icons/fugue/gear.png", "alt" => ""}
										%ul{"class" => "dropdown-menu pull-right custom"}
											- @list_drop = [{ :icon => "printer.png", :title => "Print chart", :divider => true}.as_json,
											{ :icon => "gear.png", :title => "Chart settings"}.as_json,
											{ :icon => "bin-metal.png", :title => "Delete chart"}.as_json] 
											- @list_drop.each do |value|
												%li
													%a{"href" => "javascript:void(0)", "class" => "fugue"}
														%img{"src" => "/assets/icons/fugue/#{value["icon"]}"} #{value["title"]}
												- if value["divider"]
													%li.divider

									%li
										%a{"href" => "javascript:void(0)", "class" => "btn btn-mini tip", "title" =>"Save this chart"}
											%img{"src" => "/assets/icons/fugue/disk-black.png", "alt" => ""}
						.box-content
							%div{"class" => "flot flot-line"}
			.row-fluid
				.span6
					.box
						.box-head
							%h3 Recent purchases
						%div{"class" => "box-content box-nomargin"}
							%div{"class" => "alert alert-error"}
								%strong Feature!
								\Check this awesome custom animation. Click in the table on
								%strong 'mark as pending'
								\(2nd action button) !
							%table{"class" => "table table-striped table-bordered"}
								%thead
									%tr
										- @list_thead = ["Customer", "Product", "Date", "Income", "Actions"]
										- @list_thead.each do |value|
											%th #{value}
								%tbody
									- @list_tbody = [1, 2, 3, 4, 5]
									- @list_tbody.each do |value|
										%tr
											%td
												%a{"href" => "javascript:void(0)"} Lorem issum
											%td The awesome shirt
											%td.mobile-hide Jul 21, 2018
											%td.green + 21,4 $
											%td.actions
												.btn-group
													- @list_action = [{:icon => "magnifier.png", :title => "Show details"}.as_json,
													{:icon => "document-task.png", :title => "Mark as pending", :add_class => "animateRow"}.as_json,
													{:icon => "cross.png", :title => "Remove", "add_class" => "deleteRow"}.as_json]
													- @list_action.each do |value|
														%a{"href" => "javascript:void(0)", :class => ["btn btn-mini tip", ("#{value["add_class"]}" if value["add_class"] )], "title" => "#{value["title"]}"}
															%img{"src" => "/assets/icons/fugue/#{value["icon"]}"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ENT Software Center
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    / = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:rel => "shortcut icon", "href" => "/assets/favicon/favicon.png"}
    <script src="/assets/fromtemplate/jquery.js"></script>
    <script src="/assets/fromtemplate/less.js"></script>
    <script src="/assets/fromtemplate/bootstrap.min.js"></script>
    <script src="/assets/fromtemplate/jquery.peity.js"></script>
    <script src="/assets/fromtemplate/jquery.fancybox.js"></script>
    <script src="/assets/fromtemplate/jquery.flot.js"></script>
    <script src="/assets/fromtemplate/jquery.color.js"></script>
    <script src="/assets/fromtemplate/jquery.flot.resize.js"></script>
    <script src="/assets/fromtemplate/jquery.cookie.js"></script>
    <script src="/assets/fromtemplate/custom.js"></script>
    <script src="/assets/fromtemplate/demo.js"></script>
  %body{:class => ("login_body" if request.env['PATH_INFO'] == login_path)}
    = yield

app/views/users/_user.html.haml
%tr
  %td= user.id
  %td
    = link_to user.name, user_path(user)

app/views/users/index.html.haml
.container
  .row
    .col-lg-12.text-center
      %h1.title LOGIN APP
    .col-lg-12.form-group
      %label{:for => ""} Welcome
      = link_to current_user.name, user_path(current_user)
    .col-lg-12.form-group
      %label{:for => ""} List Users
      %table.table
        %thead
          %th ID
          %th User Name
        %tbody
          = render @users

app/views/users/new.html.haml
.row
  .col-lg-offset-2
    = form_for @user, html: {class: "form-horizontal"} do |f|
      .form-group
        = f.label :name, "Name", class: "col-md-2 control-label"
        .col-md-6
          = f.text_field :name, class: "form-control", placeholder: "Enter user name"
      .form-group
        = f.label :password, "Password", class: "col-md-2 control-label"
        .col-md-6
          = f.password_field :password, class: "form-control", placeholder: "Enter password"
      .form-group
        = f.label :password_confirmation, "Password Confirmation", class: "col-md-2 control-label"
        .col-md-6
          = f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password confirmation"
      .form-group
        .col-lg-offset-4
          = f.submit "Register", class: "btn btn-success"

app/views/users/show.html.haml
.container
  .row
    .col-lg-offset-3.col-lg-6
      .text-left.col-lg-6
      %label
        User name: #{@user.name}
    .text-right.col-lg-6
      = link_to "Logout", logout_path, method: :delete
  .col-lg-offset-3.col-lg-6
    = link_to "List Users", users_path